const audit1 = {
  date: 'dd.mm.yyyy',
  auditor: 'John Doe',
  month: '9',
  kat0: {
    p0: { status: 'accepted', note: '' },
    p1: { status: 'rejected', note: 'bla bla' },
    p2: { status: 'accepted', note: '' },
    p3: { status: 'rejected', note: 'Něco se mi nezdá, ale nevím co' },
    p4: { status: 'accepted', note: '' },
    p5: { status: 'rejected', note: 'třetí poznámka' },
  },
  kat1: {
    p0: { status: 'accepted', note: '' },
    p1: { status: 'accepted', note: '' },
    p2: { status: 'accepted', note: '' },
    p3: { status: 'rejected', note: '' },
    p4: { status: 'rejected', note: '' },
    p5: { status: 'rejected', note: '' },
    p6: { status: '', note: '' },
    p7: { status: '', note: '' },
  },
  kat2: {
    p0: { status: '', note: '' },
    p1: { status: '', note: '' },
    p2: { status: '', note: '' },
    p3: { status: '', note: '' },
    p4: { status: '', note: '' },
    p5: { status: '', note: '' },
    p6: { status: '', note: '' },
    p7: { status: '', note: '' },
    p8: { status: '', note: '' },
    p9: { status: '', note: '' },
  },
  kat3: {
    p0: { status: '', note: '' },
    p1: { status: '', note: '' },
    p2: { status: '', note: '' },
    p3: { status: '', note: '' },
    p4: { status: '', note: '' },
  },
  kat4: {
    p0: { status: '', note: '' },
    p1: { status: '', note: '' },
    p2: { status: '', note: '' },
    p3: { status: '', note: '' },
    p4: { status: '', note: '' },
    p5: { status: '', note: '' },
    p6: { status: '', note: '' },
  },
  kat5: {
    p0: { status: '', note: '' },
    p1: { status: '', note: '' },
    p2: { status: '', note: '' },
    p3: { status: '', note: '' },
    p4: { status: '', note: '' },
    p5: { status: '', note: '' },
    p6: { status: '', note: '' },
    p7: { status: '', note: '' },
    p8: { status: '', note: '' },
    p9: { status: '', note: '' },
  },
  kat6: {
    p0: { status: '', note: '' },
    p1: { status: '', note: '' },
    p2: { status: '', note: '' },
    p3: { status: '', note: '' },
    p4: { status: '', note: '' },
    p5: { status: '', note: '' },
  },
  kat7: {
    p0: { status: '', note: '' },
    p1: { status: '', note: '' },
    p2: { status: '', note: '' },
    p3: { status: '', note: '' },
    p4: { status: '', note: '' },
  },
  kat8: {
    p0: { status: '', note: '' },
    p1: { status: '', note: '' },
    p2: { status: '', note: '' },
    p3: { status: '', note: '' },
    p4: { status: '', note: '' },
    p5: { status: '', note: '' },
    p6: { status: '', note: '' },
    p7: { status: '', note: '' },
    p8: { status: '', note: '' },
  },
  kat9: {
    p0: { status: '', note: '' },
    p1: { status: '', note: '' },
    p2: { status: '', note: '' },
  },
  kat10: {
    p0: { status: '', note: '' },
    p1: { status: '', note: '' },
    p2: { status: '', note: '' },
    p3: { status: '', note: '' },
    p4: { status: '', note: '' },
    p5: { status: '', note: '' },
    p6: { status: '', note: '' },
    p7: { status: '', note: '' },
    p8: { status: '', note: '' },
    p9: { status: '', note: '' },
    p10: { status: '', note: '' },
  },
};
const audit2 = {
  date: 'dd.mm.yyyy',
  auditor: 'John Doe',
  month: '10',
  kat0: {
    p0: { status: 'rejected', note: '' },
    p1: { status: 'accepted', note: 'bla bla' },
    p2: { status: 'rejected', note: '' },
    p3: { status: 'accepted', note: 'Něco se mi nezdá, ale nevím co' },
    p4: { status: 'rejected', note: '' },
    p5: { status: 'accepted', note: 'třetí poznámka' },
  },
  kat1: {
    p0: { status: 'accepted', note: '' },
    p1: { status: 'accepted', note: '' },
    p2: { status: 'accepted', note: '' },
    p3: { status: 'rejected', note: '' },
    p4: { status: 'rejected', note: '' },
    p5: { status: 'rejected', note: '' },
    p6: { status: '', note: '' },
    p7: { status: '', note: '' },
  },
  kat2: {
    p0: { status: '', note: '' },
    p1: { status: '', note: '' },
    p2: { status: '', note: '' },
    p3: { status: '', note: '' },
    p4: { status: '', note: '' },
    p5: { status: '', note: '' },
    p6: { status: '', note: '' },
    p7: { status: '', note: '' },
    p8: { status: '', note: '' },
    p9: { status: '', note: '' },
  },
  kat3: {
    p0: { status: '', note: '' },
    p1: { status: '', note: '' },
    p2: { status: '', note: '' },
    p3: { status: '', note: '' },
    p4: { status: '', note: '' },
  },
  kat4: {
    p0: { status: '', note: '' },
    p1: { status: '', note: '' },
    p2: { status: '', note: '' },
    p3: { status: '', note: '' },
    p4: { status: '', note: '' },
    p5: { status: '', note: '' },
    p6: { status: '', note: '' },
  },
  kat5: {
    p0: { status: '', note: '' },
    p1: { status: '', note: '' },
    p2: { status: '', note: '' },
    p3: { status: '', note: '' },
    p4: { status: '', note: '' },
    p5: { status: '', note: '' },
    p6: { status: '', note: '' },
    p7: { status: '', note: '' },
    p8: { status: '', note: '' },
    p9: { status: '', note: '' },
  },
  kat6: {
    p0: { status: '', note: '' },
    p1: { status: '', note: '' },
    p2: { status: '', note: '' },
    p3: { status: '', note: '' },
    p4: { status: '', note: '' },
    p5: { status: '', note: '' },
  },
  kat7: {
    p0: { status: '', note: '' },
    p1: { status: '', note: '' },
    p2: { status: '', note: '' },
    p3: { status: '', note: '' },
    p4: { status: '', note: '' },
  },
  kat8: {
    p0: { status: '', note: '' },
    p1: { status: '', note: '' },
    p2: { status: '', note: '' },
    p3: { status: '', note: '' },
    p4: { status: '', note: '' },
    p5: { status: '', note: '' },
    p6: { status: '', note: '' },
    p7: { status: '', note: '' },
    p8: { status: '', note: '' },
  },
  kat9: {
    p0: { status: '', note: '' },
    p1: { status: '', note: '' },
    p2: { status: '', note: '' },
  },
  kat10: {
    p0: { status: '', note: '' },
    p1: { status: '', note: '' },
    p2: { status: '', note: '' },
    p3: { status: '', note: '' },
    p4: { status: '', note: '' },
    p5: { status: '', note: '' },
    p6: { status: '', note: '' },
    p7: { status: '', note: '' },
    p8: { status: '', note: '' },
    p9: { status: '', note: '' },
    p10: { status: '', note: '' },
  },
};
const audit3 = {
  date: 'dd.mm.yyyy',
  auditor: 'John Doe',
  month: '11',
  kat0: {
    p0: { status: 'accepted', note: '' },
    p1: { status: 'rejected', note: 'bla bla' },
    p2: { status: 'accepted', note: '' },
    p3: { status: 'rejected', note: 'Něco se mi nezdá, ale nevím co' },
    p4: { status: 'accepted', note: '' },
    p5: { status: 'rejected', note: 'třetí poznámka' },
  },
  kat1: {
    p0: { status: 'accepted', note: '' },
    p1: { status: 'accepted', note: '' },
    p2: { status: 'accepted', note: '' },
    p3: { status: 'rejected', note: '' },
    p4: { status: 'rejected', note: '' },
    p5: { status: 'rejected', note: '' },
    p6: { status: '', note: '' },
    p7: { status: '', note: '' },
  },
  kat2: {
    p0: { status: '', note: '' },
    p1: { status: '', note: '' },
    p2: { status: '', note: '' },
    p3: { status: '', note: '' },
    p4: { status: '', note: '' },
    p5: { status: '', note: '' },
    p6: { status: '', note: '' },
    p7: { status: '', note: '' },
    p8: { status: '', note: '' },
    p9: { status: '', note: '' },
  },
  kat3: {
    p0: { status: '', note: '' },
    p1: { status: '', note: '' },
    p2: { status: '', note: '' },
    p3: { status: '', note: '' },
    p4: { status: '', note: '' },
  },
  kat4: {
    p0: { status: '', note: '' },
    p1: { status: '', note: '' },
    p2: { status: '', note: '' },
    p3: { status: '', note: '' },
    p4: { status: '', note: '' },
    p5: { status: '', note: '' },
    p6: { status: '', note: '' },
  },
  kat5: {
    p0: { status: '', note: '' },
    p1: { status: '', note: '' },
    p2: { status: '', note: '' },
    p3: { status: '', note: '' },
    p4: { status: '', note: '' },
    p5: { status: '', note: '' },
    p6: { status: '', note: '' },
    p7: { status: '', note: '' },
    p8: { status: '', note: '' },
    p9: { status: '', note: '' },
  },
  kat6: {
    p0: { status: '', note: '' },
    p1: { status: '', note: '' },
    p2: { status: '', note: '' },
    p3: { status: '', note: '' },
    p4: { status: '', note: '' },
    p5: { status: '', note: '' },
  },
  kat7: {
    p0: { status: '', note: '' },
    p1: { status: '', note: '' },
    p2: { status: '', note: '' },
    p3: { status: '', note: '' },
    p4: { status: '', note: '' },
  },
  kat8: {
    p0: { status: '', note: '' },
    p1: { status: '', note: '' },
    p2: { status: '', note: '' },
    p3: { status: '', note: '' },
    p4: { status: '', note: '' },
    p5: { status: '', note: '' },
    p6: { status: '', note: '' },
    p7: { status: '', note: '' },
    p8: { status: '', note: '' },
  },
  kat9: {
    p0: { status: '', note: '' },
    p1: { status: '', note: '' },
    p2: { status: '', note: '' },
  },
  kat10: {
    p0: { status: '', note: '' },
    p1: { status: '', note: '' },
    p2: { status: '', note: '' },
    p3: { status: '', note: '' },
    p4: { status: '', note: '' },
    p5: { status: '', note: '' },
    p6: { status: '', note: '' },
    p7: { status: '', note: '' },
    p8: { status: '', note: '' },
    p9: { status: '', note: '' },
    p10: { status: '', note: '' },
  },
};

const audit4 = {
  date: 'dd.mm.yyyy',
  auditor: 'John Doe',
  month: '12',
  kat0: {
    p0: { status: 'accepted', note: '' },
    p1: { status: 'rejected', note: 'bla bla' },
    p2: { status: 'accepted', note: '' },
    p3: { status: 'rejected', note: 'Něco se mi nezdá, ale nevím co' },
    p4: { status: 'accepted', note: '' },
    p5: { status: 'rejected', note: 'třetí poznámka' },
  },
  kat1: {
    p0: { status: 'accepted', note: '' },
    p1: { status: 'accepted', note: '' },
    p2: { status: 'accepted', note: '' },
    p3: { status: 'rejected', note: '' },
    p4: { status: 'rejected', note: '' },
    p5: { status: 'rejected', note: '' },
    p6: { status: '', note: '' },
    p7: { status: '', note: '' },
  },
  kat2: {
    p0: { status: '', note: '' },
    p1: { status: '', note: '' },
    p2: { status: '', note: '' },
    p3: { status: '', note: '' },
    p4: { status: '', note: '' },
    p5: { status: '', note: '' },
    p6: { status: '', note: '' },
    p7: { status: '', note: '' },
    p8: { status: '', note: '' },
    p9: { status: '', note: '' },
  },
  kat3: {
    p0: { status: '', note: '' },
    p1: { status: '', note: '' },
    p2: { status: '', note: '' },
    p3: { status: '', note: '' },
    p4: { status: '', note: '' },
  },
  kat4: {
    p0: { status: '', note: '' },
    p1: { status: '', note: '' },
    p2: { status: '', note: '' },
    p3: { status: '', note: '' },
    p4: { status: '', note: '' },
    p5: { status: '', note: '' },
    p6: { status: '', note: '' },
  },
  kat5: {
    p0: { status: '', note: '' },
    p1: { status: '', note: '' },
    p2: { status: '', note: '' },
    p3: { status: '', note: '' },
    p4: { status: '', note: '' },
    p5: { status: '', note: '' },
    p6: { status: '', note: '' },
    p7: { status: '', note: '' },
    p8: { status: '', note: '' },
    p9: { status: '', note: '' },
  },
  kat6: {
    p0: { status: '', note: '' },
    p1: { status: '', note: '' },
    p2: { status: '', note: '' },
    p3: { status: '', note: '' },
    p4: { status: '', note: '' },
    p5: { status: '', note: '' },
  },
  kat7: {
    p0: { status: '', note: '' },
    p1: { status: '', note: '' },
    p2: { status: '', note: '' },
    p3: { status: '', note: '' },
    p4: { status: '', note: '' },
  },
  kat8: {
    p0: { status: '', note: '' },
    p1: { status: '', note: '' },
    p2: { status: '', note: '' },
    p3: { status: '', note: '' },
    p4: { status: '', note: '' },
    p5: { status: '', note: '' },
    p6: { status: '', note: '' },
    p7: { status: '', note: '' },
    p8: { status: '', note: '' },
  },
  kat9: {
    p0: { status: '', note: '' },
    p1: { status: '', note: '' },
    p2: { status: '', note: '' },
  },
  kat10: {
    p0: { status: '', note: '' },
    p1: { status: '', note: '' },
    p2: { status: '', note: '' },
    p3: { status: '', note: '' },
    p4: { status: '', note: '' },
    p5: { status: '', note: '' },
    p6: { status: '', note: '' },
    p7: { status: '', note: '' },
    p8: { status: '', note: '' },
    p9: { status: '', note: '' },
    p10: { status: '', note: '' },
  },
};

const audit5 = {
  date: 'dd.mm.yyyy',
  auditor: 'John Doe',
  month: '1',
  kat0: {
    p0: { status: 'accepted', note: '' },
    p1: { status: 'rejected', note: 'bla bla' },
    p2: { status: 'accepted', note: '' },
    p3: { status: 'rejected', note: 'Něco se mi nezdá, ale nevím co' },
    p4: { status: 'accepted', note: '' },
    p5: { status: 'rejected', note: 'třetí poznámka' },
  },
  kat1: {
    p0: { status: 'accepted', note: '' },
    p1: { status: 'accepted', note: '' },
    p2: { status: 'accepted', note: '' },
    p3: { status: 'rejected', note: '' },
    p4: { status: 'rejected', note: '' },
    p5: { status: 'rejected', note: '' },
    p6: { status: '', note: '' },
    p7: { status: '', note: '' },
  },
  kat2: {
    p0: { status: '', note: '' },
    p1: { status: '', note: '' },
    p2: { status: '', note: '' },
    p3: { status: '', note: '' },
    p4: { status: '', note: '' },
    p5: { status: '', note: '' },
    p6: { status: '', note: '' },
    p7: { status: '', note: '' },
    p8: { status: '', note: '' },
    p9: { status: '', note: '' },
  },
  kat3: {
    p0: { status: '', note: '' },
    p1: { status: '', note: '' },
    p2: { status: '', note: '' },
    p3: { status: '', note: '' },
    p4: { status: '', note: '' },
  },
  kat4: {
    p0: { status: '', note: '' },
    p1: { status: '', note: '' },
    p2: { status: '', note: '' },
    p3: { status: '', note: '' },
    p4: { status: '', note: '' },
    p5: { status: '', note: '' },
    p6: { status: '', note: '' },
  },
  kat5: {
    p0: { status: '', note: '' },
    p1: { status: '', note: '' },
    p2: { status: '', note: '' },
    p3: { status: '', note: '' },
    p4: { status: '', note: '' },
    p5: { status: '', note: '' },
    p6: { status: '', note: '' },
    p7: { status: '', note: '' },
    p8: { status: '', note: '' },
    p9: { status: '', note: '' },
  },
  kat6: {
    p0: { status: '', note: '' },
    p1: { status: '', note: '' },
    p2: { status: '', note: '' },
    p3: { status: '', note: '' },
    p4: { status: '', note: '' },
    p5: { status: '', note: '' },
  },
  kat7: {
    p0: { status: '', note: '' },
    p1: { status: '', note: '' },
    p2: { status: '', note: '' },
    p3: { status: '', note: '' },
    p4: { status: '', note: '' },
  },
  kat8: {
    p0: { status: '', note: '' },
    p1: { status: '', note: '' },
    p2: { status: '', note: '' },
    p3: { status: '', note: '' },
    p4: { status: '', note: '' },
    p5: { status: '', note: '' },
    p6: { status: '', note: '' },
    p7: { status: '', note: '' },
    p8: { status: '', note: '' },
  },
  kat9: {
    p0: { status: '', note: '' },
    p1: { status: '', note: '' },
    p2: { status: '', note: '' },
  },
  kat10: {
    p0: { status: '', note: '' },
    p1: { status: '', note: '' },
    p2: { status: '', note: '' },
    p3: { status: '', note: '' },
    p4: { status: '', note: '' },
    p5: { status: '', note: '' },
    p6: { status: '', note: '' },
    p7: { status: '', note: '' },
    p8: { status: '', note: '' },
    p9: { status: '', note: '' },
    p10: { status: '', note: '' },
  },
};

const audit6 = {
  date: 'dd.mm.yyyy',
  auditor: 'John Doe',
  month: '2',
  kat0: {
    p0: { status: 'accepted', note: '' },
    p1: { status: 'accepted', note: 'bla bla' },
    p2: { status: 'accepted', note: '' },
    p3: { status: 'rejected', note: 'Něco se mi nezdá, ale nevím co' },
    p4: { status: 'rejected', note: '' },
    p5: { status: 'rejected', note: 'třetí poznámka' },
  },
  kat1: {
    p0: { status: 'accepted', note: '' },
    p1: { status: 'accepted', note: '' },
    p2: { status: 'accepted', note: '' },
    p3: { status: 'rejected', note: '' },
    p4: { status: 'rejected', note: '' },
    p5: { status: 'rejected', note: '' },
    p6: { status: '', note: '' },
    p7: { status: '', note: '' },
  },
  kat2: {
    p0: { status: '', note: '' },
    p1: { status: '', note: '' },
    p2: { status: '', note: '' },
    p3: { status: '', note: '' },
    p4: { status: '', note: '' },
    p5: { status: '', note: '' },
    p6: { status: '', note: '' },
    p7: { status: '', note: '' },
    p8: { status: '', note: '' },
    p9: { status: '', note: '' },
  },
  kat3: {
    p0: { status: '', note: '' },
    p1: { status: '', note: '' },
    p2: { status: '', note: '' },
    p3: { status: '', note: '' },
    p4: { status: '', note: '' },
  },
  kat4: {
    p0: { status: '', note: '' },
    p1: { status: '', note: '' },
    p2: { status: '', note: '' },
    p3: { status: '', note: '' },
    p4: { status: '', note: '' },
    p5: { status: '', note: '' },
    p6: { status: '', note: '' },
  },
  kat5: {
    p0: { status: '', note: '' },
    p1: { status: '', note: '' },
    p2: { status: '', note: '' },
    p3: { status: '', note: '' },
    p4: { status: '', note: '' },
    p5: { status: '', note: '' },
    p6: { status: '', note: '' },
    p7: { status: '', note: '' },
    p8: { status: '', note: '' },
    p9: { status: '', note: '' },
  },
  kat6: {
    p0: { status: '', note: '' },
    p1: { status: '', note: '' },
    p2: { status: '', note: '' },
    p3: { status: '', note: '' },
    p4: { status: '', note: '' },
    p5: { status: '', note: '' },
  },
  kat7: {
    p0: { status: '', note: '' },
    p1: { status: '', note: '' },
    p2: { status: '', note: '' },
    p3: { status: '', note: '' },
    p4: { status: '', note: '' },
  },
  kat8: {
    p0: { status: '', note: '' },
    p1: { status: '', note: '' },
    p2: { status: '', note: '' },
    p3: { status: '', note: '' },
    p4: { status: '', note: '' },
    p5: { status: '', note: '' },
    p6: { status: '', note: '' },
    p7: { status: '', note: '' },
    p8: { status: '', note: '' },
  },
  kat9: {
    p0: { status: '', note: '' },
    p1: { status: '', note: '' },
    p2: { status: '', note: '' },
  },
  kat10: {
    p0: { status: '', note: '' },
    p1: { status: '', note: '' },
    p2: { status: '', note: '' },
    p3: { status: '', note: '' },
    p4: { status: '', note: '' },
    p5: { status: '', note: '' },
    p6: { status: '', note: '' },
    p7: { status: '', note: '' },
    p8: { status: '', note: '' },
    p9: { status: '', note: '' },
    p10: { status: '', note: '' },
  },
};

module.exports = [audit1, audit2, audit3, audit4, audit5, audit6];
