module.exports = {
  kat0: {
    p0: { status: 'accepted', note: '' },
    p1: {
      status: 'rejected',
      note:
        'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nullam sit amet magna in magna gravida vehicula. Etiam dictum tincidunt diam. Fusce tellus odio, dapibus id fermentum quis, suscipit id erat. Nunc tincidunt ante vitae massa. Nulla pulvinar eleifend sem. Mauris tincidunt sem sed arcu. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus luctus egestas leo. Sed ac dolor sit amet purus malesuada congue. Nunc tincidunt ante vitae massa. Quisque porta.',
    },
    p2: { status: 'accepted', note: '' },
    p3: { status: 'rejected', note: 'Něco se mi nezdá, ale nevím co' },
    p4: { status: 'accepted', note: '' },
    p5: { status: 'rejected', note: 'třetí poznámka' },
  },
  kat1: {
    p0: { status: 'accepted', note: '' },
    p1: { status: 'accepted', note: '' },
    p2: { status: 'accepted', note: '' },
    p3: { status: 'rejected', note: '' },
    p4: { status: 'rejected', note: '' },
    p5: { status: 'rejected', note: '' },
    p6: { status: '', note: '' },
    p7: { status: '', note: '' },
  },
  kat2: {
    p0: { status: '', note: '' },
    p1: { status: '', note: '' },
    p2: { status: '', note: '' },
    p3: { status: '', note: '' },
    p4: { status: '', note: '' },
    p5: { status: '', note: '' },
    p6: { status: '', note: '' },
    p7: { status: '', note: '' },
    p8: { status: '', note: '' },
    p9: { status: '', note: '' },
  },
  kat3: {
    p0: { status: '', note: '' },
    p1: { status: '', note: '' },
    p2: { status: '', note: '' },
    p3: { status: '', note: '' },
    p4: { status: '', note: '' },
  },
  kat4: {
    p0: { status: '', note: '' },
    p1: { status: '', note: '' },
    p2: { status: '', note: '' },
    p3: { status: '', note: '' },
    p4: { status: '', note: '' },
    p5: { status: '', note: '' },
    p6: { status: '', note: '' },
  },
  kat5: {
    p0: { status: '', note: '' },
    p1: { status: '', note: '' },
    p2: { status: '', note: '' },
    p3: { status: '', note: '' },
    p4: { status: '', note: '' },
    p5: { status: '', note: '' },
    p6: { status: '', note: '' },
    p7: { status: '', note: '' },
    p8: { status: '', note: '' },
    p9: { status: '', note: '' },
  },
  kat6: {
    p0: { status: '', note: '' },
    p1: { status: '', note: '' },
    p2: { status: '', note: '' },
    p3: { status: '', note: '' },
    p4: { status: '', note: '' },
    p5: { status: '', note: '' },
  },
  kat7: {
    p0: { status: '', note: '' },
    p1: { status: '', note: '' },
    p2: { status: '', note: '' },
    p3: { status: '', note: '' },
    p4: { status: '', note: '' },
  },
  kat8: {
    p0: { status: '', note: '' },
    p1: { status: '', note: '' },
    p2: { status: '', note: '' },
    p3: { status: '', note: '' },
    p4: { status: '', note: '' },
    p5: { status: '', note: '' },
    p6: { status: '', note: '' },
    p7: { status: '', note: '' },
    p8: { status: '', note: '' },
  },
  kat9: {
    p0: { status: '', note: '' },
    p1: { status: '', note: '' },
    p2: { status: '', note: '' },
  },
  kat10: {
    p0: { status: '', note: '' },
    p1: { status: '', note: '' },
    p2: { status: '', note: '' },
    p3: { status: '', note: '' },
    p4: { status: '', note: '' },
    p5: { status: '', note: '' },
    p6: { status: '', note: '' },
    p7: { status: '', note: '' },
    p8: { status: '', note: '' },
    p9: { status: '', note: '' },
    p10: { status: '', note: '' },
  },
};
